ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Rem Bomb Base"
ENT.Author = "Remorse"
ENT.Category = "ZCity Other"
ENT.Spawnable = false
ENT.AdminSpawnable = false
ENT.IsRemBomb = true
ENT.Model = "models/damik/500lb.mdl"
ENT.ExplosionRadius = 1000
ENT.ExplosionDamage = 300
ENT.Decal = "scorch_big"
ENT.Effect = "doi_stuka_explosion"
ENT.EffectAir = "doi_stuka_explosion"
ENT.EffectWater = "ins_water_explosion"
ENT.ExplosionSound = {"ied/ied_detonate_01.wav", "ied/ied_detonate_02.wav", "ied/ied_detonate_03.wav"}
ENT.FarExplosionSound = {"ied/ied_detonate_dist_01.wav", "ied/ied_detonate_dist_02.wav", "ied/ied_detonate_dist_03.wav"}
ENT.WaterSound = "iedins/water/ied_water_detonate_01.wav"
ENT.WaterFarSound = "iedins/water/ied_water_detonate_01.wav"
ENT.ArmSound = "npc/roller/mine/rmine_blip3.wav"
ENT.ShouldExplodeOnImpact = true
ENT.TraceLength = 400
ENT.ImpactSpeed = 200
ENT.Mass = 500
ENT.Life = 50
ENT.ArmDelay = 0.1
ENT.PhysForce = 50000
ENT.PhysLift = 20000
